### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by nishi7409** [nishi7409/CourseCal#8]
- Login
- Sign up
- User dashboard
- Admin dashboard (?) <-- probably not needed since we have access to the console

**Comment by johnnthough** [comment]
Hi
I am a UI/UX designer and i would be happy to help

**Comment by nishi7409** [comment]
Hey,

We mainly communicate over Discord. Do you have an account?

**Comment by johnnthough** [comment]
Ok i am sending the request now

**Comment by johnnthough** [comment]
Okechi Emezue#0617 , its not finding you so you can just add me

**Comment by johnnthough** [comment]
sent the request

**Comment by nishi7409** [comment]
I’ll just figure this out on the fly lol
